apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mlc-llm-deployment
spec: 
  replicas : 8
  selector:
    matchLabels:
      app: mlc-llm-service
  template:
    metadata:
      labels:
        app: mlc-llm-service
    spec:
      containers:
      - name: mlc-llm-serve
        image: mlc-llm-serve:v2
        ports: 
        - containerPort: 8000
        env:
        - name: NUM_REPLICAS
          value: "8"
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "16Gi"
            nvidia.com/gpu: 1