apiVersion: v1
kind: Service
metadata:
  name: mlc-llm-service
  labels:
    app: mlc-llm-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: mlc-llm-service